#!/bin/bash

# Daniel M. Lofaro (dan@danlofaro.com)

SCREEN_NAME_DAEMON="sophia-process-daemon"
SCREEN_NAME_DAEMON_USB0="sophia-process-daemon-usb0"
SCREEN_NAME_DAEMON_USB1="sophia-process-daemon-usb1"
SCREEN_NAME_ACC="sophia-process-acc"
ROOT_DIR=/etc/visir/
ROOT_DIR_ROBOT_REF=$ROOT_DIR/python
ROOT_DIR_ROBOT=$ROOT_DIR/python
BIN_ROBOT_NAME_REF=visir_robot_ref_run.sh
BIN_ROBOT_NAME_STATE=visir_robot_state_run.sh
BIN_ENABLE_FWD=enable_fwd.sh
BIN_ENABLE_AFT=enable_aft.sh
BIN_DISABLE_FWD=disable_fwd.sh
BIN_DISABLE_AFT=disable_aft.sh
BIN_ROBOT_SONAR=visir_robot_sonar_run.sh

DIR_PYTHON_SCRIPT=/etc/sophia/python/
SCRIPT_PYTHON_RUN=run.sh
PYTHON_SOPHIA_DAEMON_ROS=lofaroDynamixel2_ros2.py
SCRIPT_SOPHIA_DAEMON_ROS=sophia-daemon.sh
SCRIPT_SOPHIA_DAEMON_ROS_USB0=sophia-daemon-usb0.sh
SCRIPT_SOPHIA_DAEMON_ROS_USB1=sophia-daemon-usb1.sh
SCRIPT_SOPHIA_ACC_ROS=sophia-acc.sh
DIR_TMP=/tmp
SOPHIA_TMP=$DIR_TMP/sophia-tmp.sh
touch $SOPHIA_TMP
chmod +x $SOPHIA_TMP

SOPHIA_SERIAL=/dev/ttyUSB0
SOPHIA_SERIAL0=/dev/ttyUSB0
SOPHIA_SERIAL1=/dev/ttyUSB1
SOPHIA_ACC_SERIAL=/dev/ttyACM0


Start()
{
  case "$1" in
  # Robot Side
	'robot' )
          	Start daemon
		Start acc
	;;

	'daemon' )
          	Start daemon0
          	Start daemon1
	;;
	'daemonLegacy' )
		setserial $SOPHIA_SERIAL low_latency
                THE_NAME=$SCREEN_NAME_DAEMON
                THE_BIN=$SCRIPT_SOPHIA_DAEMON_ROS
                THE_ROOT_DIR=$DIR_PYTHON_SCRIPT
	;;
	'daemon0' )
		setserial $SOPHIA_SERIAL0 low_latency
                THE_NAME=$SCREEN_NAME_DAEMON_USB0
                THE_BIN=$SCRIPT_SOPHIA_DAEMON_ROS_USB0
                THE_ROOT_DIR=$DIR_PYTHON_SCRIPT
	;;
	'daemon1' )
		setserial $SOPHIA_SERIAL1 low_latency
                THE_NAME=$SCREEN_NAME_DAEMON_USB1
                THE_BIN=$SCRIPT_SOPHIA_DAEMON_ROS_USB1
                THE_ROOT_DIR=$DIR_PYTHON_SCRIPT
	;;

	'acc' )
		setserial $SOPHIA_ACC_SERIAL low_latency
                THE_NAME=$SCREEN_NAME_ACC
                THE_BIN=$SCRIPT_SOPHIA_ACC_ROS
                THE_ROOT_DIR=$DIR_PYTHON_SCRIPT
	;;

	*)
		ShowUsage
		exit 1
	;;
   esac

   if ! screen -list | grep -q $THE_NAME; then
   # 'Starting Robot Process'
     cd $THE_ROOT_DIR
     screen -S $THE_NAME -d -m ./$THE_BIN
   fi
   sleep 1
   Status $1
}

Stop()
{
  case "$1" in
  # Robot Side
	'robot' )
                Stop daemon
     		Stop acc
	;;
	'daemon' )
                Stop daemon0
		Stop daemon1
	;;
	'daemonLegacy' )
                THE_NAME=$SCREEN_NAME_DAEMON
	;;
	'daemon0' )
                THE_NAME=$SCREEN_NAME_DAEMON_USB0
	;;
	'daemon1' )
                THE_NAME=$SCREEN_NAME_DAEMON_USB1
	;;
	'acc' )
                THE_NAME=$SCREEN_NAME_ACC
	;;


	*)
		ShowUsage
		exit 1
	;;
  esac
  screen -S $THE_NAME -p 0 -X quit
  sleep 1
  Status $1
}

Status()
{
  case "$1" in
  # Robot Side
	'robot' )
                Status daemon
		Status acc
	;;
	'daemon' )
                Status daemon0
		Status daemon1
	;;
	'daemonLegacy' )
                THE_NAME=$SCREEN_NAME_DAEMON
	;;
	'daemon0' )
                THE_NAME=$SCREEN_NAME_DAEMON0
	;;
	'daemon1' )
                THE_NAME=$SCREEN_NAME_DAEMON1
	;;
	'acc' )
                THE_NAME=$SCREEN_NAME_ACC
	;;

	*)
		ShowUsage
		exit 1
	;;
  esac
  if ! screen -list | grep -q $THE_NAME; then
  # 'Starting Robot Process'
    echo 'Process NOT running'
  else
    echo 'Process running'
  fi
}


Run()
{
  if [ -z $1 ]
  then
    ShowUsage
    exit 1
  else
    source $DIR_PYTHON_SCRIPT/$SCRIPT_PYTHON_RUN $1
  fi
}

ShowUsage()
{
	echo
        echo '------------------------------------------------'
        echo '------------------------------------------------'
        echo '-----------SOPHIA DAEMON AND CONTROL -----------'
        echo '--------- Support: dan@danlofaro.com -----------'
        echo '------------------------------------------------'
        echo '------------------------------------------------'
	echo 'run <file name>   : Runs your python script with'
        echo '                    the Sophia includes in path '
        echo 'start             : Starts the given system     '
        echo '          <arg 0>                               '
        echo '          robot   : Starts all daemons below    '
        echo '          daemon  : Starts main daemon          ' 
        echo '          acc     : Starts accelemator process  ' 
        echo 'stop              : Stops the given system      '
        echo '          <arg 0>                               '
        echo '          robot   : Stops all daemons below     '
        echo '          daemon  : Stops main daemon           ' 
        echo '          acc     : Stops accelemator process   ' 
        echo 'run               : Runs a python script in the '
        echo '                    Sophia work space           '
        echo '          <arg 0>                               '
        echo '          foo.py  : any set of bash arguements  '
#        echo 'run               : Runs a command in the sophia'
#        echo '                    work space                  '
#        echo '          <arg 0>                               '
#        echo '          a0..aN  : any set of bash arguements  '
	echo '(no-arg)          : This message'
	echo
}


case "$1" in
# Runs Python Script
	'run' )
		Run ${@:2}
	;;

        'start' )
		Start $2
	;;

        'stop' )
		Stop $2
	;;

        'status' )
		Status $2
	;;

	*)
		ShowUsage
		exit 1
	;;
esac

exit 0

# Local Variables:
#  indent-tabs-mode:t
#  tab-width: 8
#  c-basic-offset: 8
# End:
