#!/bin/bash

# Daniel M. Lofaro (dan@danlofaro.com)

SCREEN_NAME_DAEMON="sophia-process-daemon"
ROOT_DIR=/etc/visir/
ROOT_DIR_ROBOT_REF=$ROOT_DIR/python
ROOT_DIR_ROBOT=$ROOT_DIR/python
BIN_ROBOT_NAME_REF=visir_robot_ref_run.sh
BIN_ROBOT_NAME_STATE=visir_robot_state_run.sh
BIN_ENABLE_FWD=enable_fwd.sh
BIN_ENABLE_AFT=enable_aft.sh
BIN_DISABLE_FWD=disable_fwd.sh
BIN_DISABLE_AFT=disable_aft.sh
BIN_ROBOT_SONAR=visir_robot_sonar_run.sh

DIR_PYTHON_SCRIPT=/etc/sophia/python/
SCRIPT_PYTHON_RUN=run.sh
PYTHON_SOPHIA_DAEMON_ROS=lofaroDynamixel2_ros2.py
SCRIPT_SOPHIA_DAEMON_ROS=sophia-daemon.sh
DIR_TMP=/tmp
SOPHIA_TMP=$DIR_TMP/sophia-tmp.sh
touch $SOPHIA_TMP
chmod +x $SOPHIA_TMP

Enable()
{
  case "$1" in 
        'robot')
		Enable fwd
		Enable aft
	;;
	'fwd')
		THE_BIN=$BIN_ENABLE_FWD
                THE_ROOT_DIR=$ROOT_DIR_ROBOT_REF
	;;

	'aft')
		THE_BIN=$BIN_ENABLE_AFT
                THE_ROOT_DIR=$ROOT_DIR_ROBOT_REF
	;;

	*)
		ShowUsage
		exit 1
	;;
   esac
   cd $ROOT_DIR_ROBOT_REF
   source $THE_BIN
   
}

Disable()
{
  case "$1" in 
	'robot')
		Disable fwd
		Disable aft
	;;
	'fwd')
		THE_BIN=$BIN_DISABLE_FWD
                THE_ROOT_DIR=$ROOT_DIR_ROBOT_REF
	;;

	'aft')
		THE_BIN=$BIN_DISABLE_AFT
                THE_ROOT_DIR=$ROOT_DIR_ROBOT_REF
	;;

	*)
		ShowUsage
		exit 1
	;;
   esac
   cd $ROOT_DIR_ROBOT_REF
   source $THE_BIN
   
}

Start()
{
  case "$1" in
  # Robot Side
	'robot' )
          	Start daemon
	;;

	'daemon' )
                THE_NAME=$SCREEN_NAME_DAEMON
                THE_BIN=$SCRIPT_SOPHIA_DAEMON_ROS
                THE_ROOT_DIR=$DIR_PYTHON_SCRIPT
	;;

	*)
		ShowUsage
		exit 1
	;;
   esac

   if ! screen -list | grep -q $THE_NAME; then
   # 'Starting Robot Process'
     cd $THE_ROOT_DIR
     screen -S $THE_NAME -d -m ./$THE_BIN
   fi
   sleep 1
   Status $1
}

Stop()
{
  case "$1" in
  # Robot Side
	'robot' )
                Stop ref
     		Stop state
		Stop sonar
	;;
	'daemon' )
                THE_NAME=$SCREEN_NAME_DAEMON
	;;

	*)
		ShowUsage
		exit 1
	;;
  esac
  screen -S $THE_NAME -p 0 -X quit
  sleep 1
  Status $1
}

Status()
{
  case "$1" in
  # Robot Side
	'robot' )
                Status ref
		Status state
		Status sonar
	;;
	'daemon' )
                THE_NAME=$SCREEN_NAME_DAEMON
	;;

	*)
		ShowUsage
		exit 1
	;;
  esac
  if ! screen -list | grep -q $THE_NAME; then
  # 'Starting Robot Process'
    echo 'Process NOT running'
  else
    echo 'Process running'
  fi
}


Run()
{
  if [ -z $1 ]
  then
    ShowUsage
    exit 1
  else
    source $DIR_PYTHON_SCRIPT/$SCRIPT_PYTHON_RUN $1
  fi
}

ShowUsage()
{
	echo
        echo '------------------------------------------------'
        echo '------------------------------------------------'
        echo '-----------SOPHIA DAEMON AND CONTROL -----------'
        echo '--------- Support: dan@danlofaro.com -----------'
        echo '------------------------------------------------'
        echo '------------------------------------------------'
	echo 'run <file name>   : Runs your python script with'
        echo '                    the Sophia includes in path '
        echo 'start             : Starts the given system     '
        echo '          <arg 0>                               '
        echo '          daemon  : Starts main daemon          ' 
        echo 'stop              : Stops the given system      '
        echo '          <arg 0>                               '
        echo '          daemon  : Stops main daemon           ' 
	echo '(no-arg)          : This message'
	echo
}


case "$1" in
# Runs Python Script
	'run' )
		Run $2
	;;

        'start' )
		Start $2
	;;

        'stop' )
		Stop $2
	;;

	*)
		ShowUsage
		exit 1
	;;
esac

exit 0

# Local Variables:
#  indent-tabs-mode:t
#  tab-width: 8
#  c-basic-offset: 8
# End:
